### ISSUE TITLE
One or both of the following parameters are missing: serverUrl or report

### ISSUE THREAD

**Issue by tuminzee** [nfqsolutions/ngx-tableau#1]
I have mentioned both the parameters yet I get this error

####  component.html

```
  <ngx-tableau
    [tableauVizUrl]="url"
    [serverUrl]="serverUrl"
    [report]="report"
  ></ngx-tableau>
```

#### component.ts
```

  url: "https://public.tableau.com/views/Sehat-IntelVisualization/MainParametersDistribution;
  serverUrl="https://public.tableau.com";
  report="Sehat-IntelVisualization/MainParametersDistribution";

```

![image](https://user-images.githubusercontent.com/58180803/114076101-e7353280-98c3-11eb-9587-5b79b3d73ff5.png)

**Comment by hmartos** [comment]
Hi Tumin,

The problem here seems to be that you have unclosed double quotes in the `url` variable in `component.ts`.

Here is a working [Stackblitz](https://stackblitz.com/edit/ngx-tableau-issue-1?file=src/app/app.component.ts).

Also, I realized that you are informing `tableauVizUrl`, `serverUrl`, and `report` at the same time. The intended behavior is that if you inform `tableauVizUrl` the other two parameters shouldn't be required, and if you inform `serverUrl` and `report`, `tableauVizUrl` shouldn't be required. The first case is not working as expected and it's not very well documented, so I'll check it and publish a new release.

Thanks for using the module, let me know if you have further problems.

**Comment by tuminzee** [comment]
Thank you so much for responding, I was using only `tableauVizUrl`, but as I received an error stating that you have not provided the paraneters of `serverUrl ` or `report` that I why I added it.

I would like to state the problem in detail. 
I have attached a screenshot of the dashboard. 
During the first time view of the component, everything would be fine; the problem starts when I switch components. 
i.e, When I would go from one component, and back to the tableau component. I would get this error. 
And If I would refresh the page, the error would be gone. 
I hope this makes sense. 
I appreciate you taking time for this issue. 
Have a good day :)

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'ngx-tableau-dashboard',
  template: `
            <div class="tableau-dashboard">
                <ngx-tableau
                [tableauVizUrl]="url"
                [serverUrl]="serverUrl"
                [report]="report"
                ></ngx-tableau>
          </div>
  `,
  styleUrls: ['./tableau-dashboard.component.scss']
})
export class TableauDashboardComponent implements OnInit {
  url= "https://public.tableau.com/views/Sehat-IntelVisualization/MainParametersDistribution";
  serverUrl="https://public.tableau.com"
  report="Sehat-IntelVisualization/MainParametersDistribution"
  constructor() { }

  ngOnInit(): void {
  }

}
```


![image](https://user-images.githubusercontent.com/58180803/114262737-3764df80-99ff-11eb-8dbc-91842dee4331.png)
![image](https://user-images.githubusercontent.com/58180803/114262748-4481ce80-99ff-11eb-8abb-a9c7ab1a50c5.png)

![ezgif-3-829c32e53982](https://user-images.githubusercontent.com/58180803/114262808-a9d5bf80-99ff-11eb-8ecf-019c8ce5c6dd.gif)

**Comment by hmartos** [comment]
Hi again, Tumin

I have been able to reproduce the issue, but it took me some time since I needed to update the old host Angular App I used to develop this module. I will investigate the issue and will come back to you with a new release that solves it.

The issue is happening because the variables defined in the controller seem to be received by `ngx-tableau` as undefined in the second load of the component. For now, you can make a quick and dirty fix passing the values of `serverUrl` and `report` directly in the template of the component

```html
<ngx-tableau 
  serverUrl="https://public.tableau.com" 
  report="Sehat-IntelVisualization/MainParametersDistribution">
</ngx-tableau>
```

I have created a new [Stackblitz](https://stackblitz.com/edit/angular-9qil6t?file=src%2Fapp%2Fcrisis-center%2Fcrisis-center-home%2Fcrisis-center-home.component.html) with an Angular Router. Navigate between Heroes and Crisis Center routes to try it.

I'll let you know when the new release is ready.

**Comment by tuminzee** [comment]
> Hi again, Tumin
> 
> I have been able to reproduce the issue, but it took me some time since I needed to update the old host Angular App I used to develop this module. I will investigate the issue and will come back to you with a new release that solves it.
> 
> The issue is happening because the variables defined in the controller seem to be received by `ngx-tableau` as undefined in the second load of the component. For now, you can make a quick and dirty fix passing the values of `serverUrl` and `report` directly in the template of the component
> 
> ```
> <ngx-tableau 
>   serverUrl="https://public.tableau.com" 
>   report="Sehat-IntelVisualization/MainParametersDistribution">
> </ngx-tableau>
> ```
> 
> I have created a new [Stackblitz](https://stackblitz.com/edit/angular-9qil6t?file=src%2Fapp%2Fcrisis-center%2Fcrisis-center-home%2Fcrisis-center-home.component.html) with an Angular Router. Navigate between Heroes and Crisis Center routes to try it.
> 
> I'll let you know when the new release is ready.

Thank you so much!
It works just fine. I appreciate you taking time for resolving this issue. 

I am eagerly waiting for the new release.
I wish you a good weekend.

**Comment by hmartos** [comment]
Hi, Tumin

I just wanted to let you know that the new release 1.1.1 is ready and should be working fine. I have updated the latest [Stackblitz](https://stackblitz.com/edit/angular-9qil6t?file=src%2Fapp%2Fcrisis-center%2Fcrisis-center-home%2Fcrisis-center-home.component.ts) so you can have a working example.

Let me know if you have further problems.

Thanks for this first issue!

**Comment by tuminzee** [comment]
I am so excited about it already!
Good work!
![image](https://user-images.githubusercontent.com/58180803/114317232-bd2e7b00-9b24-11eb-9c3f-00aceecfb1c0.png)
